name: azure-ml-databricks-ml-project
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21.0
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - azureml-sdk=1.34.0
  - databricks-api=0.16.0
  - jupyterlab=3.0.14
  - pip:
      - azureml-core==1.34.0
      - azureml-mlflow==1.34.0
      - pytest==6.2.4
      - black==21.7b0