paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  model_output: "models/output"
  logs: "logs"
hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 100
features:
  feature_set: "features/feature_set.csv"
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score