model:
  name: TideDynamicPricing
  version: 1.0
  parameters:
    learning_rate: 0.01
    n_estimators: 100
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
  features:
    - price
    - demand
    - competitor_price
    - seasonality
    - promotions
  target: final_price

environment:
  python_version: 3.8
  dependencies:
    - pandas
    - numpy
    - scikit-learn
    - mlflow
    - azure-keyvault-secrets
    - logging

logging:
  level: INFO
  format: json
  handlers:
    - console
    - file
  file_path: logs/dynamic_pricing.log

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: TideDynamicPricingExperiment